### ISSUE TITLE
Zend\Mvc\Service\* contains hidden dependencies

### ISSUE THREAD

**Issue by SvenRtbg** [zendframework/zend-mvc#10]
The dependencies of this module are not correctly declared. They are:

```
"require": {
    "php": ">=5.3.23",
    "zendframework/zend-eventmanager": "~2.5",
    "zendframework/zend-servicemanager": "~2.5",
    "zendframework/zend-form": "~2.5",
    "zendframework/zend-stdlib": "~2.5"
},
```

However, simply requiring zend-mvc with Composer does not put the result into a usable state. There are plenty of hidden dependencies to other modules. For example, the ModuleManagerFactory requires zend-modulemanager and zend-log to be present. I believe there is a hint of what is still missing in require-dev:

```
"require-dev": {
    "zendframework/zend-authentication": "~2.5",
    "zendframework/zend-cache": "~2.5",
    "zendframework/zend-console": "~2.5",
    "zendframework/zend-di": "~2.5",
    "zendframework/zend-filter": "~2.5",
    "zendframework/zend-http": "~2.5",
    "zendframework/zend-i18n": "~2.5",
    "zendframework/zend-inputfilter": "~2.5",
    "zendframework/zend-json": "~2.5",
    "zendframework/zend-log": "~2.5",
    "zendframework/zend-modulemanager": "~2.5",
    "zendframework/zend-session": "~2.5",
    "zendframework/zend-serializer": "~2.5",
    "zendframework/zend-text": "~2.5",
    "zendframework/zend-uri": "~2.5",
    "zendframework/zend-validator": "~2.5",
    "zendframework/zend-version": "~2.5",
    "zendframework/zend-view": "~2.5",
    "fabpot/php-cs-fixer": "1.7.*",
    "phpunit/PHPUnit": "~4.0"
},
```

My expectation: If I decide to use zend-mvc, everything that is needed to use ANY part of this module should be installed as a dependency. It does not really help to only "suggest". If I run any code, and it fails because there is a class missing, this is a dependency that I cannot choose to not install.

**Comment by gianarb** [comment]
This is your expectation (same IMO) but the community works in a different direction..
http://gianarb.it/blog/the-price-of-modularity/ I have resume it in this blogpost

**Comment by weierophinney** [comment]
The problem here is deciding what the _typical_ or _default_ path through the component is. This particular component is troublesome because there are many potential use cases for installing it:
- Maybe you just want to use the router.
- Maybe you just want to use the ResponseSender subcomponent (along with zend-http) to simplify sending various response types back to the browser.
- Maybe you want to use the Controller subcomponent for a from-scratch MVC.
- Maybe you're building on top of `Zend\Mvc\Application`.

My point is: we don't want to put _everything_ in the `require` section, only the items that will be used on every or most paths. I've personally used solely the `Router` subcomponent in projects like [phlyty](https://github.com/phly/phlyty), and have seen others do similarly. (Interestingly, I do not want or need `zend-console` as a dependency, however, even though the router supplies console routes; as such, `zend-console` is a _soft_ dependency even for routing!) If you're using this as part of the ZF2 MVC, though, you'll want the bucket list of dependencies; but, then, you're likely installing all of ZF2 at that point anyways.

(The `require-dev` section has a larger set of dependencies due to the requirement that we test _all_ functionality, not just the various subsets. Presence in the `require-dev` section does not equate to a hard dependency.)

Ideally, we'll start separating out some of this stuff into either separate components (e.g., routing) or the main ZF2 repo (e.g., service configuration), which would slim this repo down to the essentials and allow us to better determine a default set of dependencies.
