### ISSUE TITLE
Make attachments and priorities clearer

### ISSUE THREAD

**Issue by Slamdunk** [zendframework/zend-mvc#142]
Hi, it's 3 years now that I use ZF2, and before the release of MVC v3 I have to ask your thoughts about a change that, in my humble opinion, would make the logic much more easy to follow, for both newcomers and experts.

Since the day I started till now, the extensive use of `Zend\EventManager\AbstractListenerAggregate` with priorities written withing the listener buzzes and clashes me a lot, some examples:
- [ModuleRouteListener.php #L28](https://github.com/zendframework/zend-mvc/blob/release-2.7.7/src/ModuleRouteListener.php#L28): priority is decied by who uses the listener
- [RouteListener.php #L26](https://github.com/zendframework/zend-mvc/blob/release-2.7.7/src/RouteListener.php#L26): priority is never explicitly set
- [SendResponseListener.php #L77](https://github.com/zendframework/zend-mvc/blob/release-2.7.7/src/SendResponseListener.php#L77): priority is always decided by the listener

The questions are: why a listener should know when it have to be triggered? why it should know all other listener behaviour and logic flow?

An example of what is way more clear and easy to understand and follow is https://github.com/zendframework/zend-mvc/blob/release-2.7.7/src/SendResponseListener.php#L137-L141:

``` php
$events = $this->getEventManager();
$events->attach(SendResponseEvent::EVENT_SEND_RESPONSE, new PhpEnvironmentResponseSender(), -1000);
$events->attach(SendResponseEvent::EVENT_SEND_RESPONSE, new ConsoleResponseSender(), -2000);
$events->attach(SendResponseEvent::EVENT_SEND_RESPONSE, new SimpleStreamResponseSender(), -3000);
$events->attach(SendResponseEvent::EVENT_SEND_RESPONSE, new HttpResponseSender(), -4000);
```

Here (note: a different EventManager context, but same theory) the listeners encapsulate their behaviour, but the user decieds when they have to be exectued.

What I propose (and I can PR something too if agreed) is:
1. make all `ListenerAggregate`s unaware of priority and just use the argument
2. explicit listener priorities during a build phase

This for:
1. [Application::bootstrap #L150-L157](https://github.com/zendframework/zend-mvc/blob/release-2.7.7/src/Application.php#L150-L157)
2. [View\Http\ViewManager #L94-L126](https://github.com/zendframework/zend-mvc/blob/release-2.7.7/src/View/Http/ViewManager.php#L94-L126) (as of yet is partial)
3. [Service\ViewFactory #L31-L32](https://github.com/zendframework/zend-mvc/blob/release-2.7.7/src/Service/ViewFactory.php#L31-L32) also done in [View\Http\ViewManager #L233](https://github.com/zendframework/zend-mvc/blob/release-2.7.7/src/View/Http/ViewManager.php#L233)
4. [Service\ModuleManagerFactory](https://github.com/zendframework/zend-mvc/blob/release-2.7.7/src/Service/ModuleManagerFactory.php) (requires change of zend-modulemanager listeners)

Some listeners define different priorities for different events.
As far as I investigated, all these cases should be split in different listeners, tighted togher with some dependancy, example: [Zend\ModuleManager\Listener\LocatorRegistrationListener](https://github.com/zendframework/zend-modulemanager/blob/release-2.7.2/src/Listener/LocatorRegistrationListener.php).

I would also argue that the listener shouldn't know the event name of their callback for the same logic, making the whole idea of ListenerAggregate dubious, but better make one step at time, and let's start with the priorities.

**Comment by weierophinney** [comment]
Priorities serve two purposes:
- They allow ordering of listeners. In zend-mvc and zend-modulemanager in particular, order is often quite important, particularly as listeners can short-circuit execution.
- Having fine-grained priority allows users to push their own listeners onto the stack in specific locations within the event workflow. To use your example of the `SendResponseEvent` above, a developer could push an alternate console response sender that operates at -1000, ensuring it triggers first.

I will not argue that there are not problems with this approach — when we were working on Apigility, I had to at some point create a flow diagram detailing what listeners were attached, and at which priority, in order to understand where to push new listeners to ensure they trigger at the correct time. This is a bit of a documentation nightmare.

That said, _changing the system at this time would break the majority of listeners that exist._ Yes, we'll be tagging a new major version, and this is the time to break backwards compatibility; however, we're also simultaneously trying to provide a reasonable upgrade path for users, and breaking things needlessly, without a way to prepare code while running under v2, is a non-starter for us.

If you want to get rid of priorities, the solution is to use a middleware stack such as Expressive instead of zend-mvc.

I'm open to re-visiting this topic in the future, but not for zend-mvc v3, which I'm on the verge of tagging currently.
