### ISSUE TITLE
Get AbstractPlugin in AbstractPlugin

### ISSUE THREAD

**Issue by albrin** [zendframework/zend-mvc#180]
**I use plugins like API for my components.**

When I call method of plugin in controller — it works.

```
// Сontroller
class CatalogController extends AbstractActionController
{
    // Action
    public function indexAction()
    {
        // Getting plugin in my controller and call a function — OK
        $this->AlbrinPersonalSaleUser()->add();
    }
}
```

But if I try to call method of plugin in another plugin:

```
// My plugin
class AlbrinPersonalCart extends AbstractPlugin
{
    public function getBasketUserId()
    {
        // I receive an error
        $id = $this->AlbrinPersonalSaleUser()->add();
    }
}
```

Error message

```
Call to undefined method AlbrinPersonal\Controller\Plugin\AlbrinPersonalCart::AlbrinPersonalSaleUser()
```

Can I use plugin another plugin, without passing additional objects?

**P.S.: Temporarily, I found the following solution**

```
// My plugin
class AlbrinPersonalCart extends AbstractPlugin
{
    public function getBasketUserId()
    {
                $albrinPersonalSaleUserPlugin = $this->getController()->getPluginManager()->get('AlbrinPersonalSaleUser');
                $id = $albrinPersonalSaleUserPlugin->add();
    }
}
```

**Comment by samsonasik** [comment]
The better way is you inject the plugin:

``` php
class AlbrinPersonalCart extends AbstractPlugin
{
       private $albrinPersonalSaleUser;
       public function __construct(AlbrinPersonalSaleUser $albrinPersonalSaleUser)
       {
              $this->albrinPersonalSaleUser = $albrinPersonalSaleUser;
       } 
}
```

and then, you can use factory for it:

``` php
'AlbrinPersonalCart' => function(\Zend\Mvc\PluginManager $manager) {
         $plugin  = new AlbrinPersonalCart($manager->get('AlbrinPersonalSaleUser'));
         return $plugin;
},
```

I think it is `not` an issue ;). close-able ;)

**Comment by albrin** [comment]
I am developing an engine for online store and other components for integration with multiple services on Zend Framework.

It is planned that the components can be any number. For example, forty components. Each component may have a different number of plugins — API.

Components must be loosely and able to communicate with each other through the API.

Therefore, each time to do such injections will be difficult:

```
'AlbrinPersonalCart' => function(\Zend\Mvc\PluginManager $manager) {
         $plugin  = new AlbrinPersonalCart($manager->get('AlbrinPersonalSaleUser'));
         return $plugin;
},
```

**Comment by weierophinney** [comment]
Plugins are not seeded with the plugin manager; only controllers are, which is why you cannot do method overloading to retrieve them.

You have three options:
- inject your plugins with the plugins on which they depend, as @samsonasik suggested. This is the best option, as it ensures there are no hidden dependencies, encourages and facilitates testing, and allows for easy substitutions via alternate factories.
- Create an alternate abstract plugin base that accepts the plugin manager; plugins can then pull other plugins from that. Use an initializer or delegator factory to inject the plugin manager automatically.
- Plugins already compose the controller that calls them, so you can also pull plugins from that: `$this->getController()->plugjnName()`.

**Comment by bhartimukesh01** [comment]
Hi samsonasik,

Please let us know where (which file)  we inject the below code for calling plugin into another plugin as i am new to zend 3.

'AlbrinPersonalCart' => function(\Zend\Mvc\PluginManager $manager) {
         $plugin  = new AlbrinPersonalCart($manager->get('AlbrinPersonalSaleUser'));
         return $plugin;
},

Thanks
