### ISSUE TITLE
Routing problem

### ISSUE THREAD

**Issue by forethoughtde** [zendframework/zend-mvc#214]
# Question:
### Resource: From Zend getting started tutorial
I have following actions:
1. index
2. add
3. edit
4. delete
I have set up the routes like below and had problems getting to /album/add. Can anyone here please explain me why I could not get to the /album[/action] routes?

```php
'router' => [
        'routes' => [
            'albumOperation' => [
                'type'    => Segment::class,
                'options' => [
                    'route' => '/album[/:action[/:id]]',
                    'constraints' => [
                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                        'id'     => '[0-9]+',
                    ],
                    'defaults' => [
                        'controller' => Controller\AlbumController::class,
                        'action'     => 'index',
                    ],
                ],
'album' => [
                'type'    => Literal::class,
                'options' => [
                    'route' => '/album',
                    'defaults' => [
                        'controller' => Controller\AlbumController::class,
                        'action'     => 'index',
                    ],
                ],
            ],
        ],
    ]
```

**Comment by froschdesign** [comment]
> …had problems getting to /album/add.

Would you like to create the URLs?
Add this to your view script:
```php
<a href="<?= $this->url('album') ?>">List albums</a>
<a href="<?= $this->url('album', ['action' => 'add']) ?>">Add new album</a>
<a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">Edit</a>
```
See also in the tutorial: [Database and models – Listing albums](https://docs.zendframework.com/tutorials/getting-started/database-and-models/#listing-albums)

The second route definition is not needed, because the first route points already to the index action.
Delete the route with name "album" and rename your route "albumOperation" to "album". ([Please compare with the tutorial!](https://zendframework.github.io/tutorials/getting-started/routing-and-controllers/#routing-and-controllers))

**Comment by froschdesign** [comment]
Btw. If you have problems with the tutorial, please use the [repository of the tutorial](https://github.com/zendframework/tutorials).

**Comment by forethoughtde** [comment]
I have created URLs but the links are just album. The following line does not create album\edit URI. 

`<a href="<?= $this->url('album', ['action' => 'add']) ?>">Add new album</a>
`
Once I delete the albumOperations route and modified the album to the following code: it started working. 

```
'album' => [
                'type'    => Segment::class,
                'options' => [
                    'route' => '/album[/:action[/:id]]',
                    'constraints' => [
                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                        'id'     => '[0-9]+',
                    ],
                    'defaults' => [
                        'controller' => Controller\AlbumController::class,
                        'action'     => 'index',
                    ],
                ]
```
I would like to know why was the former code not working? Is it because album is used in the $this->url() method?

**Comment by froschdesign** [comment]
> I would like to know why was the former code not working? Is it because album is used in the $this->url() method?

Your old "album" route points always to the "index" action, because you defined the target:

```php
'defaults' => [
    'controller' => Controller\AlbumController::class,
    'action'     => 'index',
],
```

…and do not allow any parameters with the route type "Literal".

With the original "album" route from the tutorial it is possible to route to more then the "index" action. Please look at the [explanation under the first code example](https://docs.zendframework.com/tutorials/getting-started/routing-and-controllers/).
