### ISSUE TITLE
getting Call to a member function toArray() on array in Plugin/FlashMessenger.php on line 306

### ISSUE THREAD

**Issue by michaelwolfram93** [zendframework/zend-mvc#73]
Hi,

I'm getting this error, if I call $flashMessenger->render in my custom view helper. FlashMessages will be added in controller by $this->flashMessenger()->addErrorMessage(...) etc.

The Problem is solved, after i replaced line 306 by following code:

```
        if(is_array($this->messages[$namespace])) {
          return $this->messages[$namespace];
        } else {
          return $this->messages[$namespace]->toArray();
        }
```

I use this package in version 2.6.2  and zendframework/zendframework in version 2.5.3

**Comment by weierophinney** [comment]
While I appreciate that you found a "fix", the problem is that it masks the root cause somewhere.

When messages are added, they are pushed on to an `SplQueue` instance. As such, the real question is: how is an array sneaking into the `$messages[$namespace]` value? We need to find how that is happening.

Can you give the exact sequence of code that demonstrates the problem, please, so I can try and reproduce this in a test?

**Comment by michaelwolfram93** [comment]
hi weierophinney,

I have added an error message to flashMessenger in one of my controllers:

`$this->flashMessenger()->addErrorMessage('ERROR_MESSAGE');
      $this->redirect()->toUrl('/admin/course/overview/index');
      return false;`

These messages will be rendered by a custom ViewHelper:

```
class FlashMessageHelper extends AbstractHelper {

public function __invoke(FlashMessenger $flashMessenger) {

$flashMessenger->setMessageOpenFormat('<div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><p class="text-center">');

$flashMessenger->setMessageSeparatorString('</p><p class="text-center">');

$flashMessenger->setMessageCloseString('</p></div>');

$flashMessenger->setAutoEscape(false);

echo $flashMessenger->render('error', array(
    'alert',
    'alert-dismissible',
    'alert-danger'
));
echo $flashMessenger->render('info', array(
    'alert',
    'alert-dismissible',
    'alert-info'
));
echo $flashMessenger->render('default', array(
    'alert',
    'alert-dismissible',
    'alert-warning'
));
echo $flashMessenger->render('success', array(
    'alert',
    'alert-dismissible',
    'alert-success'
));
}
}
```

I have dumped the content of $this->messages. A success-message contains following:

`(
    [success] => Zend\Stdlib\SplQueue Object
        (
            [flags:SplDoublyLinkedList:private] => 4
            [dllist:SplDoublyLinkedList:private] => Array
                (
                    [0] => SUCCESS_MESSAGE
                )
        )
)`

The same call at different time generates following content:

`(
    [success] => Array
        (
            [0] => SUCCESS_MESSAGE
        )
)
`

**Comment by weierophinney** [comment]
> The same call at different time generates following content:

That's interesting — do you mean at a later time in the same request? or a later request? I ask, because flash messages are expected typically to be retrieved exactly once; any later retrieval should result in an empty set. I'd expect to see what you received on the first result, and then any later retrievals to be empty.

I hate to keep bugging for more information, but I still don't have enough to produce a reproduce case. How exactly do you get the second result?

**Comment by DanielBeltran** [comment]
Hi there,
I have the same problem with fm->getMessages() and fm->getCurrentMessages().
As the error not occurs with ->getMessages() as described above it uses to happen with getCurrentMessages(). I looked into Flashmessenger code and it hasnt changed since last Version so the bug might not be rooted here.
I also get that bug in the return Method of getCurrentMessages() and as i debugged it turned out ($container->{$namespace}) is not a SPLQueue but an array....
So i looked into the addMessage Method but it turns out that messages are added correctly since getMessages works and getCurrentMessages throws that error. So there might be a session problem?
Therefore it is not a SPLQueue but an array toArray return error toarray called on array... i called toarray earlier in the addMessage Method and it correctly returned empty...
Hope that information helps track down the root of this bug.

**Comment by michaelwolfram93** [comment]
@weierophinney,

I mean a later request, but the same action, with same parameters. Maybe, the informations of DanialBetran are more helpful?

**Comment by danmarinescu79** [comment]
Hello , 

if you clear the current messages `$flashMessenger->clearCurrentMessages();` after the last echo the issue with your custom helper is appear to be fixed

**Comment by exptom** [comment]
I'm getting this exact same problem when using the flash messenger in a ZF3 mvc project. It seems that after the redirect the session is being repopulated with an array rather than an arrayobject.
I've added an issue against the plugin repo itself.

**Comment by m0rg** [comment]
i commented on https://github.com/zendframework/zend-mvc-plugin-flashmessenger/issues/9 with my theory of why this is happening. Try using SessionArrayStorage with SanSessionToolbar. I am able to reproduce it.

**Comment by m0rg** [comment]
samsonaik fixed it, and now i can't reproduce it anymore (sansessiontoolbar 1.0.5)

**Comment by samsonasik** [comment]
@michaelwolfram93 can be closed now
