### ISSUE TITLE
Would it be possible to zf3 to load the module, which is required for the current router?

### ISSUE THREAD

**Issue by googlle** [zendframework/zend-mvc#77]
My app always loads all the modules, and starts the onBootstrap() all the modules in order. Would it be possible to zf3 to load the module, which is required for the current router? And models from other modules to load using autoload

**Comment by weierophinney** [comment]
No, it's not possible. By design.

The intent is for module classes to be lightweight and provide information to the application specifically around two areas:
- configuration, _including routing configuration_
- listeners for MVC (and other) events

Autoloading _can_ be provided by modules as well, but does not have to be. You can already setup autoloading rules for modules using composer or an application-level autoloader, and most third-party modules do this already. 

If your module only provides classes, all you need is an autoloader. But if it provides configuration and/or wires event listeners, a Module class is required; it's how the module is able to provide those details to the application.
