### ISSUE TITLE
Question: Why is E_USER_DEPRECATED used in stead of E_DEPRECATED?

### ISSUE THREAD

**Issue by Rud5G** [zendframework/zend-mvc#98]
In my production php.ini the error_reporting settings are: 

```
; Default Value: E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED
; Development Value: E_ALL
; Production Value: E_ALL & ~E_DEPRECATED & ~E_STRICT
; http://php.net/error-reporting
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
```

This does not filter the E_USER_DEPRECATED triggered in https://github.com/zendframework/zend-mvc/blob/master/src/Service/ServiceManagerConfig.php#L127

**Comment by Rud5G** [comment]
Maybe i should have added this to #88

**Comment by weierophinney** [comment]
Because `E_DEPRECATED` can only be triggered by PHP itself, to indicate deprecated functionality in the PHP engine itself. For userland code (_including_ frameworks and libraries!) to trigger deprecation notices, you must use `E_USER_DEPRECATED`.

BTW, you can add that to the `error_reporting` mask, too:

``` ini
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_USER_DEPRECATED
```

**Comment by Rud5G** [comment]
Thanks!, just wanted to be sure.
